MATCHES = {
    1: {
        "timestamp": 1528988400,
        "round": 1,
        "goals_home": 5,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Rússia",
        "team_home_en": "Russia",
        "team_home_id": 26,
        "team_visitor": "Arábia Saudita",
        "team_visitor_en": "Saudi Arabia",
        "team_visitor_id": 2,
        "stadium": "Luzhniki Stadium",
        "stadium_lat": 55.72,
        "stadium_long": 37.55,
        "prefix_fifa_home": "RUS",
        "prefix_fifa_visitor": "KSA"
    },
    2: {
        "timestamp": 1529064000,
        "round": 1,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Egito",
        "team_home_en": "Egypt",
        "team_home_id": 12,
        "team_visitor": "Uruguai",
        "team_visitor_en": "Uruguay",
        "team_visitor_id": 32,
        "stadium": "Ekaterinburg Arena",
        "stadium_lat": 56.83,
        "stadium_long": 60.57,
        "prefix_fifa_home": "EGY",
        "prefix_fifa_visitor": "URU"
    },
    3: {
        "timestamp": 1529074800,
        "round": 1,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Marrocos",
        "team_home_en": "Morocco",
        "team_home_id": 19,
        "team_visitor": "Irã",
        "team_visitor_en": "IR Iran",
        "team_visitor_id": 16,
        "stadium": "Saint Petersburg Stadium",
        "stadium_lat": 59.97,
        "stadium_long": 30.22,
        "prefix_fifa_home": "MAR",
        "prefix_fifa_visitor": "IRN"
    },
    4: {
        "timestamp": 1529085600,
        "round": 1,
        "goals_home": 3,
        "goals_visitor": 3,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Portugal",
        "team_home_en": "Portugal",
        "team_home_id": 25,
        "team_visitor": "Espanha",
        "team_visitor_en": "Spain",
        "team_visitor_id": 13,
        "stadium": "Fisht Stadium",
        "stadium_lat": 43.4,
        "stadium_long": 39.96,
        "prefix_fifa_home": "POR",
        "prefix_fifa_visitor": "ESP"
    },
    5: {
        "timestamp": 1529143200,
        "round": 1,
        "goals_home": 2,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "França",
        "team_home_en": "France",
        "team_home_id": 14,
        "team_visitor": "Austrália",
        "team_visitor_en": "Australia",
        "team_visitor_id": 4,
        "stadium": "Kazan Arena",
        "stadium_lat": 55.82,
        "stadium_long": 49.16,
        "prefix_fifa_home": "FRA",
        "prefix_fifa_visitor": "AUS"
    },
    6: {
        "timestamp": 1529154000,
        "round": 1,
        "goals_home": 1,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Argentina",
        "team_home_en": "Argentina",
        "team_home_id": 3,
        "team_visitor": "Islândia",
        "team_visitor_en": "Iceland",
        "team_visitor_id": 17,
        "stadium": "Spartak Stadium",
        "stadium_lat": 55.82,
        "stadium_long": 37.44,
        "prefix_fifa_home": "ARG",
        "prefix_fifa_visitor": "ISL"
    },
    7: {
        "timestamp": 1529164800,
        "round": 1,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Peru",
        "team_home_en": "Peru",
        "team_home_id": 23,
        "team_visitor": "Dinamarca",
        "team_visitor_en": "Denmark",
        "team_visitor_id": 11,
        "stadium": "Mordovia Arena",
        "stadium_lat": 54.18,
        "stadium_long": 45.2,
        "prefix_fifa_home": "PER",
        "prefix_fifa_visitor": "DEN"
    },
    8: {
        "timestamp": 1529175600,
        "round": 1,
        "goals_home": 2,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Croácia",
        "team_home_en": "Croatia",
        "team_home_id": 10,
        "team_visitor": "Nigéria",
        "team_visitor_en": "Nigeria",
        "team_visitor_id": 21,
        "stadium": "Kaliningrad Stadium",
        "stadium_lat": 54.7,
        "stadium_long": 20.53,
        "prefix_fifa_home": "CRO",
        "prefix_fifa_visitor": "NGA"
    },
    9: {
        "timestamp": 1529236800,
        "round": 1,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Costa Rica",
        "team_home_en": "Costa Rica",
        "team_home_id": 9,
        "team_visitor": "Sérvia",
        "team_visitor_en": "Serbia",
        "team_visitor_id": 28,
        "stadium": "Samara Arena",
        "stadium_lat": 53.28,
        "stadium_long": 50.24,
        "prefix_fifa_home": "CRC",
        "prefix_fifa_visitor": "SRB"
    },
    10: {
        "timestamp": 1529247600,
        "round": 1,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Alemanha",
        "team_home_en": "Germany",
        "team_home_id": 1,
        "team_visitor": "México",
        "team_visitor_en": "Mexico",
        "team_visitor_id": 20,
        "stadium": "Luzhniki Stadium",
        "stadium_lat": 55.72,
        "stadium_long": 37.55,
        "prefix_fifa_home": "GER",
        "prefix_fifa_visitor": "MEX"
    },
    11: {
        "timestamp": 1529258400,
        "round": 1,
        "goals_home": 1,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Brasil",
        "team_home_en": "Brazil",
        "team_home_id": 6,
        "team_visitor": "Suíça",
        "team_visitor_en": "Switzerland",
        "team_visitor_id": 30,
        "stadium": "Rostov Arena",
        "stadium_lat": 47.21,
        "stadium_long": 39.74,
        "prefix_fifa_home": "BRA",
        "prefix_fifa_visitor": "SUI"
    },
    12: {
        "timestamp": 1529323200,
        "round": 1,
        "goals_home": 1,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Suécia",
        "team_home_en": "Sweden",
        "team_home_id": 29,
        "team_visitor": "Coreia do Sul",
        "team_visitor_en": "Korea Republic",
        "team_visitor_id": 8,
        "stadium": "Nizhny Novgorod Stadium",
        "stadium_lat": 56.34,
        "stadium_long": 43.96,
        "prefix_fifa_home": "SWE",
        "prefix_fifa_visitor": "KOR"
    },
    13: {
        "timestamp": 1529334000,
        "round": 1,
        "goals_home": 3,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Bélgica",
        "team_home_en": "Belgium",
        "team_home_id": 5,
        "team_visitor": "Panamá",
        "team_visitor_en": "Panama",
        "team_visitor_id": 22,
        "stadium": "Fisht Stadium",
        "stadium_lat": 43.4,
        "stadium_long": 39.96,
        "prefix_fifa_home": "BEL",
        "prefix_fifa_visitor": "PAN"
    },
    14: {
        "timestamp": 1529344800,
        "round": 1,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Tunísia",
        "team_home_en": "Tunisia",
        "team_home_id": 31,
        "team_visitor": "Inglaterra",
        "team_visitor_en": "England",
        "team_visitor_id": 15,
        "stadium": "Volgograd Arena",
        "stadium_lat": 48.73,
        "stadium_long": 44.55,
        "prefix_fifa_home": "TUN",
        "prefix_fifa_visitor": "ENG"
    },
    15: {
        "timestamp": 1529409600,
        "round": 1,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Colômbia",
        "team_home_en": "Colombia",
        "team_home_id": 7,
        "team_visitor": "Japão",
        "team_visitor_en": "Japan",
        "team_visitor_id": 18,
        "stadium": "Mordovia Arena",
        "stadium_lat": 54.18,
        "stadium_long": 45.2,
        "prefix_fifa_home": "COL",
        "prefix_fifa_visitor": "JPN"
    },
    16: {
        "timestamp": 1529420400,
        "round": 1,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Polônia",
        "team_home_en": "Poland",
        "team_home_id": 24,
        "team_visitor": "Senegal",
        "team_visitor_en": "Senegal",
        "team_visitor_id": 27,
        "stadium": "Spartak Stadium",
        "stadium_lat": 55.82,
        "stadium_long": 37.44,
        "prefix_fifa_home": "POL",
        "prefix_fifa_visitor": "SEN"
    },
    17: {
        "timestamp": 1529431200,
        "round": 2,
        "goals_home": 3,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Rússia",
        "team_home_en": "Russia",
        "team_home_id": 26,
        "team_visitor": "Egito",
        "team_visitor_en": "Egypt",
        "team_visitor_id": 12,
        "stadium": "Saint Petersburg Stadium",
        "stadium_lat": 59.97,
        "stadium_long": 30.22,
        "prefix_fifa_home": "RUS",
        "prefix_fifa_visitor": "EGY"
    },
    18: {
        "timestamp": 1529496000,
        "round": 2,
        "goals_home": 1,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Portugal",
        "team_home_en": "Portugal",
        "team_home_id": 25,
        "team_visitor": "Marrocos",
        "team_visitor_en": "Morocco",
        "team_visitor_id": 19,
        "stadium": "Luzhniki Stadium",
        "stadium_lat": 55.72,
        "stadium_long": 37.55,
        "prefix_fifa_home": "POR",
        "prefix_fifa_visitor": "MAR"
    },
    19: {
        "timestamp": 1529506800,
        "round": 2,
        "goals_home": 1,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Uruguai",
        "team_home_en": "Uruguay",
        "team_home_id": 32,
        "team_visitor": "Arábia Saudita",
        "team_visitor_en": "Saudi Arabia",
        "team_visitor_id": 2,
        "stadium": "Rostov Arena",
        "stadium_lat": 47.21,
        "stadium_long": 39.74,
        "prefix_fifa_home": "URU",
        "prefix_fifa_visitor": "KSA"
    },
    20: {
        "timestamp": 1529517600,
        "round": 2,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Irã",
        "team_home_en": "IR Iran",
        "team_home_id": 16,
        "team_visitor": "Espanha",
        "team_visitor_en": "Spain",
        "team_visitor_id": 13,
        "stadium": "Kazan Arena",
        "stadium_lat": 55.82,
        "stadium_long": 49.16,
        "prefix_fifa_home": "IRN",
        "prefix_fifa_visitor": "ESP"
    },
    21: {
        "timestamp": 1529582400,
        "round": 2,
        "goals_home": 1,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Dinamarca",
        "team_home_en": "Denmark",
        "team_home_id": 11,
        "team_visitor": "Austrália",
        "team_visitor_en": "Australia",
        "team_visitor_id": 4,
        "stadium": "Samara Arena",
        "stadium_lat": 53.28,
        "stadium_long": 50.24,
        "prefix_fifa_home": "DEN",
        "prefix_fifa_visitor": "AUS"
    },
    22: {
        "timestamp": 1529593200,
        "round": 2,
        "goals_home": 1,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "França",
        "team_home_en": "France",
        "team_home_id": 14,
        "team_visitor": "Peru",
        "team_visitor_en": "Peru",
        "team_visitor_id": 23,
        "stadium": "Ekaterinburg Arena",
        "stadium_lat": 56.83,
        "stadium_long": 60.57,
        "prefix_fifa_home": "FRA",
        "prefix_fifa_visitor": "PER"
    },
    23: {
        "timestamp": 1529604000,
        "round": 2,
        "goals_home": 0,
        "goals_visitor": 3,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Argentina",
        "team_home_en": "Argentina",
        "team_home_id": 3,
        "team_visitor": "Croácia",
        "team_visitor_en": "Croatia",
        "team_visitor_id": 10,
        "stadium": "Nizhny Novgorod Stadium",
        "stadium_lat": 56.34,
        "stadium_long": 43.96,
        "prefix_fifa_home": "ARG",
        "prefix_fifa_visitor": "CRO"
    },
    24: {
        "timestamp": 1529668800,
        "round": 2,
        "goals_home": 2,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Brasil",
        "team_home_en": "Brazil",
        "team_home_id": 6,
        "team_visitor": "Costa Rica",
        "team_visitor_en": "Costa Rica",
        "team_visitor_id": 9,
        "stadium": "Saint Petersburg Stadium",
        "stadium_lat": 59.97,
        "stadium_long": 30.22,
        "prefix_fifa_home": "BRA",
        "prefix_fifa_visitor": "CRC"
    },
    25: {
        "timestamp": 1529679600,
        "round": 2,
        "goals_home": 2,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Nigéria",
        "team_home_en": "Nigeria",
        "team_home_id": 21,
        "team_visitor": "Islândia",
        "team_visitor_en": "Iceland",
        "team_visitor_id": 17,
        "stadium": "Volgograd Arena",
        "stadium_lat": 48.73,
        "stadium_long": 44.55,
        "prefix_fifa_home": "NGA",
        "prefix_fifa_visitor": "ISL"
    },
    26: {
        "timestamp": 1529690400,
        "round": 2,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Sérvia",
        "team_home_en": "Serbia",
        "team_home_id": 28,
        "team_visitor": "Suíça",
        "team_visitor_en": "Switzerland",
        "team_visitor_id": 30,
        "stadium": "Kaliningrad Stadium",
        "stadium_lat": 54.7,
        "stadium_long": 20.53,
        "prefix_fifa_home": "SRB",
        "prefix_fifa_visitor": "SUI"
    },
    27: {
        "timestamp": 1529755200,
        "round": 2,
        "goals_home": 5,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Bélgica",
        "team_home_en": "Belgium",
        "team_home_id": 5,
        "team_visitor": "Tunísia",
        "team_visitor_en": "Tunisia",
        "team_visitor_id": 31,
        "stadium": "Spartak Stadium",
        "stadium_lat": 55.82,
        "stadium_long": 37.44,
        "prefix_fifa_home": "BEL",
        "prefix_fifa_visitor": "TUN"
    },
    28: {
        "timestamp": 1529766000,
        "round": 2,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Coreia do Sul",
        "team_home_en": "Korea Republic",
        "team_home_id": 8,
        "team_visitor": "México",
        "team_visitor_en": "Mexico",
        "team_visitor_id": 20,
        "stadium": "Rostov Arena",
        "stadium_lat": 47.21,
        "stadium_long": 39.74,
        "prefix_fifa_home": "KOR",
        "prefix_fifa_visitor": "MEX"
    },
    29: {
        "timestamp": 1529776800,
        "round": 2,
        "goals_home": 2,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Alemanha",
        "team_home_en": "Germany",
        "team_home_id": 1,
        "team_visitor": "Suécia",
        "team_visitor_en": "Sweden",
        "team_visitor_id": 29,
        "stadium": "Fisht Stadium",
        "stadium_lat": 43.4,
        "stadium_long": 39.96,
        "prefix_fifa_home": "GER",
        "prefix_fifa_visitor": "SWE"
    },
    30: {
        "timestamp": 1529841600,
        "round": 2,
        "goals_home": 6,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Inglaterra",
        "team_home_en": "England",
        "team_home_id": 15,
        "team_visitor": "Panamá",
        "team_visitor_en": "Panama",
        "team_visitor_id": 22,
        "stadium": "Nizhny Novgorod Stadium",
        "stadium_lat": 56.34,
        "stadium_long": 43.96,
        "prefix_fifa_home": "ENG",
        "prefix_fifa_visitor": "PAN"
    },
    31: {
        "timestamp": 1529852400,
        "round": 2,
        "goals_home": 2,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Japão",
        "team_home_en": "Japan",
        "team_home_id": 18,
        "team_visitor": "Senegal",
        "team_visitor_en": "Senegal",
        "team_visitor_id": 27,
        "stadium": "Ekaterinburg Arena",
        "stadium_lat": 56.83,
        "stadium_long": 60.57,
        "prefix_fifa_home": "JPN",
        "prefix_fifa_visitor": "SEN"
    },
    32: {
        "timestamp": 1529863200,
        "round": 2,
        "goals_home": 0,
        "goals_visitor": 3,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Polônia",
        "team_home_en": "Poland",
        "team_home_id": 24,
        "team_visitor": "Colômbia",
        "team_visitor_en": "Colombia",
        "team_visitor_id": 7,
        "stadium": "Kazan Arena",
        "stadium_lat": 55.82,
        "stadium_long": 49.16,
        "prefix_fifa_home": "POL",
        "prefix_fifa_visitor": "COL"
    },
    34: {
        "timestamp": 1529935200,
        "round": 3,
        "goals_home": 2,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Arábia Saudita",
        "team_home_en": "Saudi Arabia",
        "team_home_id": 2,
        "team_visitor": "Egito",
        "team_visitor_en": "Egypt",
        "team_visitor_id": 12,
        "stadium": "Volgograd Arena",
        "stadium_lat": 48.73,
        "stadium_long": 44.55,
        "prefix_fifa_home": "KSA",
        "prefix_fifa_visitor": "EGY"
    },
    33: {
        "timestamp": 1529935200,
        "round": 3,
        "goals_home": 3,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Uruguai",
        "team_home_en": "Uruguay",
        "team_home_id": 32,
        "team_visitor": "Rússia",
        "team_visitor_en": "Russia",
        "team_visitor_id": 26,
        "stadium": "Samara Arena",
        "stadium_lat": 53.28,
        "stadium_long": 50.24,
        "prefix_fifa_home": "URU",
        "prefix_fifa_visitor": "RUS"
    },
    36: {
        "timestamp": 1529949600,
        "round": 3,
        "goals_home": 1,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Irã",
        "team_home_en": "IR Iran",
        "team_home_id": 16,
        "team_visitor": "Portugal",
        "team_visitor_en": "Portugal",
        "team_visitor_id": 25,
        "stadium": "Mordovia Arena",
        "stadium_lat": 54.18,
        "stadium_long": 45.2,
        "prefix_fifa_home": "IRN",
        "prefix_fifa_visitor": "POR"
    },
    35: {
        "timestamp": 1529949600,
        "round": 3,
        "goals_home": 2,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Espanha",
        "team_home_en": "Spain",
        "team_home_id": 13,
        "team_visitor": "Marrocos",
        "team_visitor_en": "Morocco",
        "team_visitor_id": 19,
        "stadium": "Kaliningrad Stadium",
        "stadium_lat": 54.7,
        "stadium_long": 20.53,
        "prefix_fifa_home": "ESP",
        "prefix_fifa_visitor": "MAR"
    },
    37: {
        "timestamp": 1530021600,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Dinamarca",
        "team_home_en": "Denmark",
        "team_home_id": 11,
        "team_visitor": "França",
        "team_visitor_en": "France",
        "team_visitor_id": 14,
        "stadium": "Luzhniki Stadium",
        "stadium_lat": 55.72,
        "stadium_long": 37.55,
        "prefix_fifa_home": "DEN",
        "prefix_fifa_visitor": "FRA"
    },
    38: {
        "timestamp": 1530021600,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Austrália",
        "team_home_en": "Australia",
        "team_home_id": 4,
        "team_visitor": "Peru",
        "team_visitor_en": "Peru",
        "team_visitor_id": 23,
        "stadium": "Fisht Stadium",
        "stadium_lat": 43.4,
        "stadium_long": 39.96,
        "prefix_fifa_home": "AUS",
        "prefix_fifa_visitor": "PER"
    },
    39: {
        "timestamp": 1530036000,
        "round": 3,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Islândia",
        "team_home_en": "Iceland",
        "team_home_id": 17,
        "team_visitor": "Croácia",
        "team_visitor_en": "Croatia",
        "team_visitor_id": 10,
        "stadium": "Rostov Arena",
        "stadium_lat": 47.21,
        "stadium_long": 39.74,
        "prefix_fifa_home": "ISL",
        "prefix_fifa_visitor": "CRO"
    },
    40: {
        "timestamp": 1530036000,
        "round": 3,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Nigéria",
        "team_home_en": "Nigeria",
        "team_home_id": 21,
        "team_visitor": "Argentina",
        "team_visitor_en": "Argentina",
        "team_visitor_id": 3,
        "stadium": "Saint Petersburg Stadium",
        "stadium_lat": 59.97,
        "stadium_long": 30.22,
        "prefix_fifa_home": "NGA",
        "prefix_fifa_visitor": "ARG"
    },
    42: {
        "timestamp": 1530108000,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 3,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "México",
        "team_home_en": "Mexico",
        "team_home_id": 20,
        "team_visitor": "Suécia",
        "team_visitor_en": "Sweden",
        "team_visitor_id": 29,
        "stadium": "Ekaterinburg Arena",
        "stadium_lat": 56.83,
        "stadium_long": 60.57,
        "prefix_fifa_home": "MEX",
        "prefix_fifa_visitor": "SWE"
    },
    41: {
        "timestamp": 1530108000,
        "round": 3,
        "goals_home": 2,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Coreia do Sul",
        "team_home_en": "Korea Republic",
        "team_home_id": 8,
        "team_visitor": "Alemanha",
        "team_visitor_en": "Germany",
        "team_visitor_id": 1,
        "stadium": "Kazan Arena",
        "stadium_lat": 55.82,
        "stadium_long": 49.16,
        "prefix_fifa_home": "KOR",
        "prefix_fifa_visitor": "GER"
    },
    44: {
        "timestamp": 1530122400,
        "round": 3,
        "goals_home": 2,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Suíça",
        "team_home_en": "Switzerland",
        "team_home_id": 30,
        "team_visitor": "Costa Rica",
        "team_visitor_en": "Costa Rica",
        "team_visitor_id": 9,
        "stadium": "Nizhny Novgorod Stadium",
        "stadium_lat": 56.34,
        "stadium_long": 43.96,
        "prefix_fifa_home": "SUI",
        "prefix_fifa_visitor": "CRC"
    },
    43: {
        "timestamp": 1530122400,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Sérvia",
        "team_home_en": "Serbia",
        "team_home_id": 28,
        "team_visitor": "Brasil",
        "team_visitor_en": "Brazil",
        "team_visitor_id": 6,
        "stadium": "Spartak Stadium",
        "stadium_lat": 55.82,
        "stadium_long": 37.44,
        "prefix_fifa_home": "SRB",
        "prefix_fifa_visitor": "BRA"
    },
    45: {
        "timestamp": 1530194400,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Japão",
        "team_home_en": "Japan",
        "team_home_id": 18,
        "team_visitor": "Polônia",
        "team_visitor_en": "Poland",
        "team_visitor_id": 24,
        "stadium": "Volgograd Arena",
        "stadium_lat": 48.73,
        "stadium_long": 44.55,
        "prefix_fifa_home": "JPN",
        "prefix_fifa_visitor": "POL"
    },
    46: {
        "timestamp": 1530194400,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Senegal",
        "team_home_en": "Senegal",
        "team_home_id": 27,
        "team_visitor": "Colômbia",
        "team_visitor_en": "Colombia",
        "team_visitor_id": 7,
        "stadium": "Samara Arena",
        "stadium_lat": 53.28,
        "stadium_long": 50.24,
        "prefix_fifa_home": "SEN",
        "prefix_fifa_visitor": "COL"
    },
    48: {
        "timestamp": 1530208800,
        "round": 3,
        "goals_home": 1,
        "goals_visitor": 2,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Panamá",
        "team_home_en": "Panama",
        "team_home_id": 22,
        "team_visitor": "Tunísia",
        "team_visitor_en": "Tunisia",
        "team_visitor_id": 31,
        "stadium": "Mordovia Arena",
        "stadium_lat": 54.18,
        "stadium_long": 45.2,
        "prefix_fifa_home": "PAN",
        "prefix_fifa_visitor": "TUN"
    },
    47: {
        "timestamp": 1530208800,
        "round": 3,
        "goals_home": 0,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Inglaterra",
        "team_home_en": "England",
        "team_home_id": 15,
        "team_visitor": "Bélgica",
        "team_visitor_en": "Belgium",
        "team_visitor_id": 5,
        "stadium": "Kaliningrad Stadium",
        "stadium_lat": 54.7,
        "stadium_long": 20.53,
        "prefix_fifa_home": "ENG",
        "prefix_fifa_visitor": "BEL"
    },
    49: {
        "timestamp": 1530367200,
        "round": 4,
        "goals_home": 4,
        "goals_visitor": 3,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "França",
        "team_home_en": "France",
        "team_home_id": 14,
        "team_visitor": "Argentina",
        "team_visitor_en": "Argentina",
        "team_visitor_id": 3,
        "stadium": "Kazan Arena",
        "stadium_lat": 55.82,
        "stadium_long": 49.16,
        "prefix_fifa_home": "FRA",
        "prefix_fifa_visitor": "ARG"
    },
    50: {
        "timestamp": 1530381600,
        "round": 4,
        "goals_home": 2,
        "goals_visitor": 1,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "FT",
        "team_home": "Uruguai",
        "team_home_en": "Uruguay",
        "team_home_id": 32,
        "team_visitor": "Portugal",
        "team_visitor_en": "Portugal",
        "team_visitor_id": 25,
        "stadium": "Fisht Stadium",
        "stadium_lat": 43.4,
        "stadium_long": 39.96,
        "prefix_fifa_home": "URU",
        "prefix_fifa_visitor": "POR"
    },
    51: {
        "timestamp": 1530453600,
        "round": 4,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Espanha",
        "team_home_en": "Spain",
        "team_home_id": 13,
        "team_visitor": "Rússia",
        "team_visitor_en": "Russia",
        "team_visitor_id": 26,
        "stadium": "Luzhniki Stadium",
        "stadium_lat": 55.72,
        "stadium_long": 37.55,
        "prefix_fifa_home": "ESP",
        "prefix_fifa_visitor": "RUS"
    },
    52: {
        "timestamp": 1530468000,
        "round": 4,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Croácia",
        "team_home_en": "Croatia",
        "team_home_id": 10,
        "team_visitor": "Dinamarca",
        "team_visitor_en": "Denmark",
        "team_visitor_id": 11,
        "stadium": "Nizhny Novgorod Stadium",
        "stadium_lat": 56.34,
        "stadium_long": 43.96,
        "prefix_fifa_home": "CRO",
        "prefix_fifa_visitor": "DEN"
    },
    53: {
        "timestamp": 1530540000,
        "round": 4,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Brasil",
        "team_home_en": "Brazil",
        "team_home_id": 6,
        "team_visitor": "México",
        "team_visitor_en": "Mexico",
        "team_visitor_id": 20,
        "stadium": "Samara Arena",
        "stadium_lat": 53.28,
        "stadium_long": 50.24,
        "prefix_fifa_home": "BRA",
        "prefix_fifa_visitor": "MEX"
    },
    54: {
        "timestamp": 1530554400,
        "round": 4,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Bélgica",
        "team_home_en": "Belgium",
        "team_home_id": 5,
        "team_visitor": "Japão",
        "team_visitor_en": "Japan",
        "team_visitor_id": 18,
        "stadium": "Rostov Arena",
        "stadium_lat": 47.21,
        "stadium_long": 39.74,
        "prefix_fifa_home": "BEL",
        "prefix_fifa_visitor": "JPN"
    },
    55: {
        "timestamp": 1530626400,
        "round": 4,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Suécia",
        "team_home_en": "Sweden",
        "team_home_id": 29,
        "team_visitor": "Suíça",
        "team_visitor_en": "Switzerland",
        "team_visitor_id": 30,
        "stadium": "Saint Petersburg Stadium",
        "stadium_lat": 59.97,
        "stadium_long": 30.22,
        "prefix_fifa_home": "SWE",
        "prefix_fifa_visitor": "SUI"
    },
    56: {
        "timestamp": 1530640800,
        "round": 4,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Colômbia",
        "team_home_en": "Colombia",
        "team_home_id": 7,
        "team_visitor": "Inglaterra",
        "team_visitor_en": "England",
        "team_visitor_id": 15,
        "stadium": "Spartak Stadium",
        "stadium_lat": 55.82,
        "stadium_long": 37.44,
        "prefix_fifa_home": "COL",
        "prefix_fifa_visitor": "ENG"
    },
    57: {
        "timestamp": 1530885600,
        "round": 5,
        "goals_home": 0,
        "goals_visitor": 0,
        "penalties_home": 0,
        "penalties_visitor": 0,
        "status": "future",
        "team_home": "Uruguai",
        "team_home_en": "Uruguay",
        "team_home_id": 32,
        "team_visitor": "França",
        "team_visitor_en": "France",
        "team_visitor_id": 14,
        "stadium": "Nizhny Novgorod Stadium",
        "stadium_lat": 56.34,
        "stadium_long": 43.96,
        "prefix_fifa_home": "URU",
        "prefix_fifa_visitor": "FRA"
    },
    58: {
        "timestamp":1530900000,
        "round":5,
        "goals_home":1,
        "goals_visitor":2,
        "penalties_home":0,
        "penalties_visitor":0,
        "status":"FT",
        "team_home":"Brasil",
        "team_home_en":"Brazil",
        "team_home_id":6,
        "team_visitor":"B\u00e9lgica",
        "team_visitor_en":"Belgium",
        "team_visitor_id":5,
        "stadium":"Fisht Stadium",
        "stadium_lat":43.4,
        "stadium_long":39.96,
        "prefix_fifa_home":"BRA",
        "prefix_fifa_visitor":"BEL"
    },
    59: {
        "timestamp":1530972000,
        "round":5,
        "goals_home":0,
        "goals_visitor":0,
        "penalties_home":0,
        "penalties_visitor":0,
        "status":"1T",
        "team_home":"Su\u00e9cia",
        "team_home_en":"Sweden",
        "team_home_id":29,
        "team_visitor":"Inglaterra",
        "team_visitor_en":"England",
        "team_visitor_id":15,
        "stadium":"Samara Arena",
        "stadium_lat":53.28,
        "stadium_long":50.24,
        "prefix_fifa_home":"SWE",
        "prefix_fifa_visitor":"ENG"
    },
    60: {
        "timestamp":1530986400,
        "round":5,
        "goals_home":0,
        "goals_visitor":0,
        "penalties_home":0,
        "penalties_visitor":0,
        "status":"future",
        "team_home":"R\u00fassia",
        "team_home_en":"Russia",
        "team_home_id":26,
        "team_visitor":"Cro\u00e1cia",
        "team_visitor_en":"Croatia",
        "team_visitor_id":10,
        "stadium":"Kazan Arena",
        "stadium_lat":55.82,
        "stadium_long":49.16,
        "prefix_fifa_home":"RUS",
        "prefix_fifa_visitor":"CRO"
    },
    61: {
        "timestamp":1531245600,
        "round":6,
        "goals_home":0,
        "goals_visitor":0,
        "penalties_home":0,
        "penalties_visitor":0,
        "status":"future",
        "team_home":"Fran\u00e7a",
        "team_home_en":"France",
        "team_home_id":14,
        "team_visitor":"B\u00e9lgica",
        "team_visitor_en":"Belgium",
        "team_visitor_id":5,
        "stadium":"Saint Petersburg Stadium",
        "stadium_lat":59.97,
        "stadium_long":30.22,
        "prefix_fifa_home":"FRA",
        "prefix_fifa_visitor":"BEL"
    }
}
